---
- name: Deploy and manage Ubuntu Container
  hosts: all
  become: yes
  vars:
    container_name: nginx_container
    image_name: nginx:latest
    host_port: 8080

  tasks:
    - name: Pull the latest Nginx image
      docker_image:
        name: "{{ image_name }}"
        source: pull 
      
    - name: Create and run the Nginx container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        ports:
          - "{{ host_port}}:80"
